[package]
name = "newsletter-signup-service"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "newsletter-signup-service"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "=4.0.0-rc.3"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4.19", features = ["serde"] }
sqlx = { version = "0.5.11", features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"] }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
uuid = { version = "0.8", features = ["serde", "v4"] }
config = "0.12.0"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1"
secrecy = { version = "0.8", features = ["serde"] }
tracing-actix-web = "=0.5.0-rc.3"


[dev-dependencies]
reqwest = "0.11"
once_cell = "1"