services:
  # A Docker web service
  - type: web
    name: newsletter-signup-service
    env: docker
    region: oregon
    plan: starter
    numInstances: 1
    healthCheckPath: /health_check
    envVars:
      - key: TEST
        value: atest
      - key: APP_DATABASE__USERNAME
        fromDatabse:
          name: newsletter-signup-service-db
          property: user
      - key: APP_DATABASE__PASSWORD
        fromDatabse:
          name: newsletter-signup-service-db
          property: password
      - key: APP_DATABASE__HOST
        fromDatabse:
          name: newsletter-signup-service-db
          property: host
      - key: APP_DATABASE__PORT
        fromDatabse:
          name: newsletter-signup-service-db
          property: port
      - key: APP_DATABASE__DATABASE_NAME
        fromDatabse:
          name: newsletter-signup-service-db
          property: database
databases:
  - name: newsletter-signup-service-db
    region: oregon
    databaseName: gm_newsletter
