previewsEnabled: true
previewsExpireAfterDays: 3
services:
  # A Docker web service
  - type: web
    name: newsletter-signup-service
    env: docker
    region: oregon
    plan: starter
    previewPlan: starter
    numInstances: 1
    healthCheckPath: /health_check
    envVars:
      - key: APP__DATABASE__USERNAME
        fromDatabase:
          name: newsletter-signup-service-db
          property: user
      - key: APP__DATABASE__PASSWORD
        fromDatabase:
          name: newsletter-signup-service-db
          property: password
      - key: APP__DATABASE__HOST
        fromDatabase:
          name: newsletter-signup-service-db
          property: host
      - key: APP__DATABASE__PORT
        fromDatabase:
          name: newsletter-signup-service-db
          property: port
      - key: APP__DATABASE__DATABASE_NAME
        fromDatabase:
          name: newsletter-signup-service-db
          property: database
  - type: web
    name: newsletter web app
    plan: starter
    previewPlan: starter
    env: static
    repo: https://github.com/rgarbi/gospel-message-web-app
    buildCommand: yarn build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
databases:
  - name: newsletter-signup-service-db
    plan: starter
    previewPlan: starter
    region: oregon
    databaseName: gm_newsletter
