services:
  # A Docker web service
  - type: web
    name: newsletter-signup-service
    env: docker
    region: oregon
    plan: starter
    numInstances: 1
    healthCheckPath: /health_check
    envVars:
      - key: APP__DATABASE__USERNAME
        fromDatabase:
          name: newsletter-signup-service-db
          property: user
      - key: APP__DATABASE__PASSWORD
        fromDatabase:
          name: newsletter-signup-service-db
          property: password
      - key: APP__DATABASE__HOST
        fromDatabase:
          name: newsletter-signup-service-db
          property: host
      - key: APP__DATABASE__PORT
        fromDatabase:
          name: newsletter-signup-service-db
          property: port
      - key: APP__DATABASE__DATABASE_NAME
        fromDatabase:
          name: newsletter-signup-service-db
          property: database
databases:
  - name: newsletter-signup-service-db
    plan: starter
    region: oregon
    databaseName: gm_newsletter
