# base.yaml
application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter-signup-service"
auth0config:
  audience: "https://hello-world.example.com"
  domain: "dev-4iy59-im.us.auth0.com"