application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://send.api.mailtrap.io"
  sender_email: "noreply@gospelmessage.net"
application_feature_settings:
  subscription_notification_addresses: "twadsquad@earthlink.net,thegospelmessage61@gmail.com"
