application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://api.sendgrid.com"
  sender_email: "thegospelmessage61@gmail.com"
application_feature_settings:
  subscription_notification_addresses: "['twadsquad@earthlink.net', 'thegospelmessage61@gmail.com']"