name: Build

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  SQLX_FEATURES: all

jobs:
  build:
    name: Compile, Test, fmt, Clippy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: richardgarbi/postgres-docker-more-connections:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 15s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --locked --force

      - name: Migrate database
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Check sqlx-data.json is up-to-date
        run: cargo sqlx prepare --check -- --bin newsletter-signup-service

      - name: Run cargo build
        run: cargo build

      - name: Run cargo test
        run: cargo test

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: richardgarbi/postgres-docker-more-connections:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 15s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-coverage-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-coverage-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --force

      - name: Migrate database
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          cargo install sqlx-cli --locked --force
          SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Generate coverage report
        run: cargo llvm-cov --lcov --output-path lcov.info

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: lcov.info
